# Conditions

## Signalling conditions

1. __<span style="color:red">Q</span>__: Write a wrapper around `file.remove()` that throws an error if the file to be deleted does not exist.

   __<span style="color:green">A</span>__: We have several options here. However, we prefer the following solution for its clearness and simplicity:
    
    ```{r, error = TRUE}
    file_remove_strict <- function(...) {
      if(!file.exists(...)) {
        stop("Can't delete ", `...`, " as the file doesn't exist.", call. = FALSE)
      }
      file.remove(...)
    }
    
    # Test
    saveRDS(iris, "iris.RDS")
    file_remove_strict("iris.RDS")
    file_remove_strict("iris.RDS")
    getOption("warn")
    ```

2. __<span style="color:red">Q</span>__: What does the `appendLF` argument to `message()` do? How is it related to `cat()`?

   __<span style="color:green">A</span>__: The `appendLF` argument allows to append a new line on the message. Let us illustrate this with a small example function:
   
    ```{r}
    bla <- function(appendLF = TRUE) {
      message("example message", appendLF = appendLF)
      cat("something to print")
    }
    
    bla(appendLF = TRUE)
    bla(appendLF = FALSE)
    ```

   The almost equivalent `cat()` argument is `fill`:
    
    ```{r}
    bla2 <- function(fill = TRUE) {
      cat("something to print", fill = fill)
      message("example message")
    }
    
    bla2(fill = TRUE)
    bla2(fill = FALSE)
    ```
    
   However, in both cases one can ensure a new line via `\n` at the end of the message string.

3. __<span style="color:red">Q</span>__: What does `options(error = recover)` do? Why might you use it?

   __<span style="color:green">A</span>__: In case of `options(error = recover)` `utils::recover()` will be called (without arguments) in case of an error. This will print out a list of calls which precede the error and lets the user choose to incorporate `browser()` directly in any of the regarding environments allowing a practical mode for debugging.

4. __<span style="color:red">Q</span>__: What does `options(error = quote(dump.frames(to.file = TRUE)))` do? Why might you use it?

   __<span style="color:green">A</span>__: This option writes a dump of the evaluation environment where an error occurs into a file ending on `.rda`. When this option is set, R will continue to run after the first error. To stop R at the first error use `quote({dump.frames(to.file=TRUE); q()})`. These options are especially useful for debugging non-interactive R scripts afterwards ("post mortem debugging").

## Handling conditions

1. __<span style="color:red">Q</span>__: Predict the results of evaluating the following code

    ```{r, eval = FALSE}
    show_condition <- function(code) {
      tryCatch(
        error = function(cnd) "error",
        warning = function(cnd) "warning",
        message = function(cnd) "message",
        {
          code
          NULL
        }
      )
    }
    
    show_condition(stop("!"))      # "error"
    show_condition(10)             # NULL (because no condition is signalled)
    show_condition(warning("?!"))  # "warning"
    show_condition({               
      10
      message("?")
      warning("?!")
    })                             # "message"
    ```

2. __<span style="color:red">Q</span>__: Explain the results of running this code:

    ```{r}
    withCallingHandlers(
      message = function(cnd) message("b"),
      withCallingHandlers(
        message = function(cnd) message("a"),
        message("c")
      )
    )
    ```
    
   __<span style="color:green">A</span>__: Lets look at the inner `withCallingHandlers()` first:
   The first message printed by this statement would be `a`, so the outer `withCallingHandlers` prints `b` (1). 
   Afterwards the message of the inner handler gets printed: `a` (2).
   Next the inner `withCallingHandlers()` would print `c`, so the outer `withCallingHandlers()` prints again `b` (3).
   Finally `c` (4) gets printed.

3. __<span style="color:red">Q</span>__: Read the source code for `catch_cnd()` and explain how it works.

   __<span style="color:green">A</span>__: It basically returns the default result from a wrapped `tryCatch()`, where the expression is forced and ensured that in case of no signalled condition `NULL` is returned instead of the expression's return value. This ensures that we always get the first condition in a list (containing message and call) or `NULL`.
    
    ```{r}
    rlang::catch_cnd
    ```

4. __<span style="color:red">Q</span>__: How could you rewrite `show_condition()` to use a single handler?

   __<span style="color:green">A</span>__: We can simply use the `condition` argument of `tryCatch` as shown in `rlang::catch_cond()` above:
    
    ```{r}
    show_condition2 <- function(code) {
      tryCatch(
        condition = function(cnd) {
          if (inherits(cnd, "error"))   {return("error")}
          if (inherits(cnd, "warning")) {return("warning")}
          if (inherits(cnd, "message")) {return("message")}
          },
        {
          code
          NULL
          }
      )
    }

    show_condition2(stop("!"))
    show_condition2(10)
    show_condition2(warning("?!"))
    show_condition2({
      10
      message("?")
      warning("?!")
    })
    ```
    
   If one could ensure that `"error"`, `"warning"` and `"message"` are always in the next position of the `"condition"` class, this would also work:
    
    ```{r}
    show_condition2 <- function(code) {
      tryCatch(
        condition = function(cnd) {
          class(cnd)[length(class(cnd)) - 1L]
          },
        {
          code
          NULL
        }
      )
    }
    ```

## Custom conditions

1. __<span style="color:red">Q</span>__: Inside a package, itâ€™s occassionally useful to check that a package is installed before using it. Write a function that checks if a package is installed (with `requireNamespace("pkg", quietly = FALSE))` and if not, throws a custom condition that includes the package name in the metadata.

   __<span style="color:green">A</span>__: It's quite tedious to build up this behaviour on top of `requireNamespace()`. However, if it's arguments are supplied correctly, `requiredNamespace()`'s return-behaviour can be summarised in the following way:
   
   - when the namespace was already loaded: `TRUE`
   - when the namespace was not already loaded: 
     - a message is thrown:
     - depending on success or failure `TRUE` or `FALSE` is returned.

   Therefore we adjust this behaviour only in the failure case, where we return the error condition and document the implementation with the code:
   
    ```{r}
    library(rlang)

    requireNamespace2 <- function(package)  {
      if (!is.character(package) | !length(package) == 1L) {
        abort("error_bad_argument",
              message = "`package` must be a length-1 character vector.")
      }
  
      withCallingHandlers(
        message = function(cnd)  {
          if (!requireNamespace(package, quietly = TRUE)) {
            abort(
              "error_pkg_not_found",
              message = paste0("`package` ", package, " not found."),
              package = package
            )}
        },
        requireNamespace(package, quietly = FALSE)
      )
  
      invisible(TRUE)
      }
      ```
      
      Now we can test our new function for all cases:
      
      ```{r, message = TRUE, error = TRUE}
      (requireNamespace2("base"))    # should be loaded already
      (requireNamespace2("lobstr"))  # should return a message first
      (requireNamespace2("lobstr")) 
      catch_cnd(requireNamespace2("pkg"))  # this should reutrn an error
      catch_cnd(requireNamespace2("pkg"))$package  # containing the pkg name 
      ```

2. __<span style="color:red">Q</span>__: Inside a package you often need to stop with an error when something is not right. Other packages that depend on your package might be tempted to check these errors in their unit tests. How could you help these packages to avoid relying on the error message which is part of the user interface rather than the API and might change without notice?

## Applications

1. __<span style="color:red">Q</span>__: Create `suppressConditions()` that works like `suppressMessages()` and `supressWarnings()` but supresses everything. Think carefully about how you should handle errors.

2. __<span style="color:red">Q</span>__: Compare the following two implementations of `message2error()`. What is the main advantage of `withCallingHandlers()` in this scenario? (Hint: look carefully at the traceback.)
   
    ```{r}
    message2error <- function(code) {
      withCallingHandlers(code, message = function(e) stop(e))
    }
    message2error <- function(code) {
      tryCatch(code, message = function(e) stop(e))
    }
    ```
    
   __<span style="color:green">A</span>__: 
    
3. __<span style="color:red">Q</span>__:  How would you modify the `catch_cnds()` defined if you wanted to recreate the original intermingling of warnings and messages?
   
4. __<span style="color:red">Q</span>__:  Why is catching interrupts dangerous? Run this code to find out.

    ```{r, eval = FALSE}
    bottles_of_beer <- function(i = 99) {
      message("There are ", i, " bottles of beer on the wall, ", i, " bottles of beer.")
      while(i > 0) {
        tryCatch(
          Sys.sleep(1),
          interrupt = function(err) {
            i <<- i - 1
            if (i > 0) {
              message(
                "Take one down, pass it around, ", i, 
                " bottle", if (i > 1) "s", " of beer on the wall."
              )
            }
          }
        )
      }
      message("No more bottles of beer on the wall, no more bottles of beer.")
    }
    ```
